### ISSUE TITLE
Process finished with exit code 1 in watch mode 

### ISSUE THREAD

**Issue by KBraNet** [evo-mark/vite-plugin-gutenberg-blocks#8]
Process finished with exit code 1 in watch mode when we  when we make a mistake in the script or viewScript

```
build started...
✘ [ERROR] Expected ";" but found "new"

    src/viewScript.js:5:27:
      5 │     const accordion = test new;
        │                            ~~~
        ╵                            ;

/Users/front-it/www/gutenbergblocks/wp-content/plugins/gutenberg-blocks/vite-plugin-gutenberg-blocks/node_modules/esbuild/lib/main.js:1649
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
src/viewScript.js:5:27: ERROR: Expected ";" but found "new"
    at failureErrorWithLog (/Users/front-it/www/gutenbergblocks/wp-content/plugins/gutenberg-blocks/vite-plugin-gutenberg-blocks/node_modules/esbuild/lib/main.js:1649:15)
    at /Users/front-it/www/gutenbergblocks/wp-content/plugins/gutenberg-blocks/vite-plugin-gutenberg-blocks/node_modules/esbuild/lib/main.js:1058:25
    at runOnEndCallbacks (/Users/front-it/www/gutenbergblocks/wp-content/plugins/gutenberg-blocks/vite-plugin-gutenberg-blocks/node_modules/esbuild/lib/main.js:1484:45)
    at buildResponseToResult (/Users/front-it/www/gutenbergblocks/wp-content/plugins/gutenberg-blocks/vite-plugin-gutenberg-blocks/node_modules/esbuild/lib/main.js:1056:7)
    at /Users/front-it/www/gutenbergblocks/wp-content/plugins/gutenberg-blocks/vite-plugin-gutenberg-blocks/node_modules/esbuild/lib/main.js:1085:16
    at responseCallbacks.<computed> (/Users/front-it/www/gutenbergblocks/wp-content/plugins/gutenberg-blocks/vite-plugin-gutenberg-blocks/node_modules/esbuild/lib/main.js:703:9)
    at handleIncomingPacket (/Users/front-it/www/gutenbergblocks/wp-content/plugins/gutenberg-blocks/vite-plugin-gutenberg-blocks/node_modules/esbuild/lib/main.js:762:9)
    at Socket.readFromStdout (/Users/front-it/www/gutenbergblocks/wp-content/plugins/gutenberg-blocks/vite-plugin-gutenberg-blocks/node_modules/esbuild/lib/main.js:679:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 27,
        file: 'src/viewScript.js',
        length: 3,
        line: 5,
        lineText: '    const accordion = test new;',
        namespace: '',
        suggestion: ';'
      },
      notes: [],
      pluginName: '',
      text: 'Expected ";" but found "new"'
    }
  ],
  warnings: []
}

Process finished with exit code 1

```

**Comment by craigrileyuk** [comment]
Thanks for the feedback.

In recent versions, the watch script will no longer exit when encountering a syntax error.
